//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForYP.DatabaseHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ICommentID { get; set; }
        public string message { get; set; }
        public Nullable<int> masterId { get; set; }
        public Nullable<int> requestId { get; set; }
    }
}
