//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("YP1Model", "FK_Request_Color", "Color", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectForYP.DatabaseHelper.Color), "Request", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectForYP.DatabaseHelper.Request), true)]
[assembly: EdmRelationshipAttribute("YP1Model", "FK_Comment_Request", "Request", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectForYP.DatabaseHelper.Request), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectForYP.DatabaseHelper.Comment), true)]
[assembly: EdmRelationshipAttribute("YP1Model", "FK_Comment_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectForYP.DatabaseHelper.User), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectForYP.DatabaseHelper.Comment), true)]
[assembly: EdmRelationshipAttribute("YP1Model", "FK__Request__Id_home__440B1D61", "HomeTechType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectForYP.DatabaseHelper.HomeTechType), "Request", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectForYP.DatabaseHelper.Request), true)]
[assembly: EdmRelationshipAttribute("YP1Model", "FK__Request__id_prob__45F365D3", "ProblemDescryption", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectForYP.DatabaseHelper.ProblemDescryption), "Request", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectForYP.DatabaseHelper.Request), true)]
[assembly: EdmRelationshipAttribute("YP1Model", "FK__Request__id_requ__46E78A0C", "RequestStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectForYP.DatabaseHelper.RequestStatus), "Request", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectForYP.DatabaseHelper.Request), true)]
[assembly: EdmRelationshipAttribute("YP1Model", "FK__User__typeId__4BAC3F29", "Type", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectForYP.DatabaseHelper.Type), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectForYP.DatabaseHelper.User), true)]

#endregion

namespace ProjectForYP.DatabaseHelper
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class YP1Entities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект YP1Entities, используя строку соединения из раздела "YP1Entities" файла конфигурации приложения.
        /// </summary>
        public YP1Entities() : base("name=YP1Entities", "YP1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта YP1Entities.
        /// </summary>
        public YP1Entities(string connectionString) : base(connectionString, "YP1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта YP1Entities.
        /// </summary>
        public YP1Entities(EntityConnection connection) : base(connection, "YP1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Color> Color
        {
            get
            {
                if ((_Color == null))
                {
                    _Color = base.CreateObjectSet<Color>("Color");
                }
                return _Color;
            }
        }
        private ObjectSet<Color> _Color;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Comment> Comment
        {
            get
            {
                if ((_Comment == null))
                {
                    _Comment = base.CreateObjectSet<Comment>("Comment");
                }
                return _Comment;
            }
        }
        private ObjectSet<Comment> _Comment;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<HomeTechType> HomeTechType
        {
            get
            {
                if ((_HomeTechType == null))
                {
                    _HomeTechType = base.CreateObjectSet<HomeTechType>("HomeTechType");
                }
                return _HomeTechType;
            }
        }
        private ObjectSet<HomeTechType> _HomeTechType;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<ProblemDescryption> ProblemDescryption
        {
            get
            {
                if ((_ProblemDescryption == null))
                {
                    _ProblemDescryption = base.CreateObjectSet<ProblemDescryption>("ProblemDescryption");
                }
                return _ProblemDescryption;
            }
        }
        private ObjectSet<ProblemDescryption> _ProblemDescryption;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Request> Request
        {
            get
            {
                if ((_Request == null))
                {
                    _Request = base.CreateObjectSet<Request>("Request");
                }
                return _Request;
            }
        }
        private ObjectSet<Request> _Request;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<RequestStatus> RequestStatus
        {
            get
            {
                if ((_RequestStatus == null))
                {
                    _RequestStatus = base.CreateObjectSet<RequestStatus>("RequestStatus");
                }
                return _RequestStatus;
            }
        }
        private ObjectSet<RequestStatus> _RequestStatus;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Type> Type
        {
            get
            {
                if ((_Type == null))
                {
                    _Type = base.CreateObjectSet<Type>("Type");
                }
                return _Type;
            }
        }
        private ObjectSet<Type> _Type;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion

        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Color. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToColor(Color color)
        {
            base.AddObject("Color", color);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Comment. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet HomeTechType. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToHomeTechType(HomeTechType homeTechType)
        {
            base.AddObject("HomeTechType", homeTechType);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet ProblemDescryption. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToProblemDescryption(ProblemDescryption problemDescryption)
        {
            base.AddObject("ProblemDescryption", problemDescryption);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Request. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRequest(Request request)
        {
            base.AddObject("Request", request);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet RequestStatus. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRequestStatus(RequestStatus requestStatus)
        {
            base.AddObject("RequestStatus", requestStatus);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet sysdiagrams. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Type. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToType(Type type)
        {
            base.AddObject("Type", type);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet User. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion

    }

    #endregion

    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="Color")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Color : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Color.
        /// </summary>
        /// <param name="id_Color">Исходное значение свойства Id_Color.</param>
        public static Color CreateColor(global::System.Int32 id_Color)
        {
            Color color = new Color();
            color.Id_Color = id_Color;
            return color;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Color
        {
            get
            {
                return _Id_Color;
            }
            set
            {
                if (_Id_Color != value)
                {
                    OnId_ColorChanging(value);
                    ReportPropertyChanging("Id_Color");
                    _Id_Color = StructuralObject.SetValidValue(value, "Id_Color");
                    ReportPropertyChanged("Id_Color");
                    OnId_ColorChanged();
                }
            }
        }
        private global::System.Int32 _Id_Color;
        partial void OnId_ColorChanging(global::System.Int32 value);
        partial void OnId_ColorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color1
        {
            get
            {
                return _Color1;
            }
            set
            {
                OnColor1Changing(value);
                ReportPropertyChanging("Color1");
                _Color1 = StructuralObject.SetValidValue(value, true, "Color1");
                ReportPropertyChanged("Color1");
                OnColor1Changed();
            }
        }
        private global::System.String _Color1;
        partial void OnColor1Changing(global::System.String value);
        partial void OnColor1Changed();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK_Request_Color", "Request")]
        public EntityCollection<Request> Request
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Request>("YP1Model.FK_Request_Color", "Request");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Request>("YP1Model.FK_Request_Color", "Request", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Comment.
        /// </summary>
        /// <param name="commentID">Исходное значение свойства CommentID.</param>
        public static Comment CreateComment(global::System.Int32 commentID)
        {
            Comment comment = new Comment();
            comment.CommentID = commentID;
            return comment;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                if (_CommentID != value)
                {
                    OnCommentIDChanging(value);
                    ReportPropertyChanging("CommentID");
                    _CommentID = StructuralObject.SetValidValue(value, "CommentID");
                    ReportPropertyChanged("CommentID");
                    OnCommentIDChanged();
                }
            }
        }
        private global::System.Int32 _CommentID;
        partial void OnCommentIDChanging(global::System.Int32 value);
        partial void OnCommentIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, true, "message");
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> masterId
        {
            get
            {
                return _masterId;
            }
            set
            {
                OnmasterIdChanging(value);
                ReportPropertyChanging("masterId");
                _masterId = StructuralObject.SetValidValue(value, "masterId");
                ReportPropertyChanged("masterId");
                OnmasterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _masterId;
        partial void OnmasterIdChanging(Nullable<global::System.Int32> value);
        partial void OnmasterIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> requestId
        {
            get
            {
                return _requestId;
            }
            set
            {
                OnrequestIdChanging(value);
                ReportPropertyChanging("requestId");
                _requestId = StructuralObject.SetValidValue(value, "requestId");
                ReportPropertyChanged("requestId");
                OnrequestIdChanged();
            }
        }
        private Nullable<global::System.Int32> _requestId;
        partial void OnrequestIdChanging(Nullable<global::System.Int32> value);
        partial void OnrequestIdChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK_Comment_Request", "Request")]
        public Request Request
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Request>("YP1Model.FK_Comment_Request", "Request").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Request>("YP1Model.FK_Comment_Request", "Request").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Request> RequestReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Request>("YP1Model.FK_Comment_Request", "Request");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Request>("YP1Model.FK_Comment_Request", "Request", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK_Comment_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("YP1Model.FK_Comment_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("YP1Model.FK_Comment_User", "User").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("YP1Model.FK_Comment_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("YP1Model.FK_Comment_User", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="HomeTechType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HomeTechType : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта HomeTechType.
        /// </summary>
        /// <param name="id_HomeTechType">Исходное значение свойства Id_HomeTechType.</param>
        public static HomeTechType CreateHomeTechType(global::System.Int32 id_HomeTechType)
        {
            HomeTechType homeTechType = new HomeTechType();
            homeTechType.Id_HomeTechType = id_HomeTechType;
            return homeTechType;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_HomeTechType
        {
            get
            {
                return _Id_HomeTechType;
            }
            set
            {
                if (_Id_HomeTechType != value)
                {
                    OnId_HomeTechTypeChanging(value);
                    ReportPropertyChanging("Id_HomeTechType");
                    _Id_HomeTechType = StructuralObject.SetValidValue(value, "Id_HomeTechType");
                    ReportPropertyChanged("Id_HomeTechType");
                    OnId_HomeTechTypeChanged();
                }
            }
        }
        private global::System.Int32 _Id_HomeTechType;
        partial void OnId_HomeTechTypeChanging(global::System.Int32 value);
        partial void OnId_HomeTechTypeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeTechType1
        {
            get
            {
                return _HomeTechType1;
            }
            set
            {
                OnHomeTechType1Changing(value);
                ReportPropertyChanging("HomeTechType1");
                _HomeTechType1 = StructuralObject.SetValidValue(value, true, "HomeTechType1");
                ReportPropertyChanged("HomeTechType1");
                OnHomeTechType1Changed();
            }
        }
        private global::System.String _HomeTechType1;
        partial void OnHomeTechType1Changing(global::System.String value);
        partial void OnHomeTechType1Changed();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__Request__Id_home__440B1D61", "Request")]
        public EntityCollection<Request> Request
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Request>("YP1Model.FK__Request__Id_home__440B1D61", "Request");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Request>("YP1Model.FK__Request__Id_home__440B1D61", "Request", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="ProblemDescryption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProblemDescryption : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта ProblemDescryption.
        /// </summary>
        /// <param name="id_ProblemDescryption">Исходное значение свойства Id_ProblemDescryption.</param>
        public static ProblemDescryption CreateProblemDescryption(global::System.Int32 id_ProblemDescryption)
        {
            ProblemDescryption problemDescryption = new ProblemDescryption();
            problemDescryption.Id_ProblemDescryption = id_ProblemDescryption;
            return problemDescryption;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_ProblemDescryption
        {
            get
            {
                return _Id_ProblemDescryption;
            }
            set
            {
                if (_Id_ProblemDescryption != value)
                {
                    OnId_ProblemDescryptionChanging(value);
                    ReportPropertyChanging("Id_ProblemDescryption");
                    _Id_ProblemDescryption = StructuralObject.SetValidValue(value, "Id_ProblemDescryption");
                    ReportPropertyChanged("Id_ProblemDescryption");
                    OnId_ProblemDescryptionChanged();
                }
            }
        }
        private global::System.Int32 _Id_ProblemDescryption;
        partial void OnId_ProblemDescryptionChanging(global::System.Int32 value);
        partial void OnId_ProblemDescryptionChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProblemDescryption1
        {
            get
            {
                return _ProblemDescryption1;
            }
            set
            {
                OnProblemDescryption1Changing(value);
                ReportPropertyChanging("ProblemDescryption1");
                _ProblemDescryption1 = StructuralObject.SetValidValue(value, true, "ProblemDescryption1");
                ReportPropertyChanged("ProblemDescryption1");
                OnProblemDescryption1Changed();
            }
        }
        private global::System.String _ProblemDescryption1;
        partial void OnProblemDescryption1Changing(global::System.String value);
        partial void OnProblemDescryption1Changed();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__Request__id_prob__45F365D3", "Request")]
        public EntityCollection<Request> Request
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Request>("YP1Model.FK__Request__id_prob__45F365D3", "Request");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Request>("YP1Model.FK__Request__id_prob__45F365D3", "Request", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="Request")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Request : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Request.
        /// </summary>
        /// <param name="requestID">Исходное значение свойства requestID.</param>
        /// <param name="startDate">Исходное значение свойства startDate.</param>
        public static Request CreateRequest(global::System.Int32 requestID, global::System.DateTime startDate)
        {
            Request request = new Request();
            request.requestID = requestID;
            request.startDate = startDate;
            return request;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 requestID
        {
            get
            {
                return _requestID;
            }
            set
            {
                if (_requestID != value)
                {
                    OnrequestIDChanging(value);
                    ReportPropertyChanging("requestID");
                    _requestID = StructuralObject.SetValidValue(value, "requestID");
                    ReportPropertyChanged("requestID");
                    OnrequestIDChanged();
                }
            }
        }
        private global::System.Int32 _requestID;
        partial void OnrequestIDChanging(global::System.Int32 value);
        partial void OnrequestIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startDate
        {
            get
            {
                return _startDate;
            }
            set
            {
                OnstartDateChanging(value);
                ReportPropertyChanging("startDate");
                _startDate = StructuralObject.SetValidValue(value, "startDate");
                ReportPropertyChanged("startDate");
                OnstartDateChanged();
            }
        }
        private global::System.DateTime _startDate;
        partial void OnstartDateChanging(global::System.DateTime value);
        partial void OnstartDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Id_homeTechType
        {
            get
            {
                return _Id_homeTechType;
            }
            set
            {
                OnId_homeTechTypeChanging(value);
                ReportPropertyChanging("Id_homeTechType");
                _Id_homeTechType = StructuralObject.SetValidValue(value, "Id_homeTechType");
                ReportPropertyChanged("Id_homeTechType");
                OnId_homeTechTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Id_homeTechType;
        partial void OnId_homeTechTypeChanging(Nullable<global::System.Int32> value);
        partial void OnId_homeTechTypeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TechModelManufaacturer
        {
            get
            {
                return _TechModelManufaacturer;
            }
            set
            {
                OnTechModelManufaacturerChanging(value);
                ReportPropertyChanging("TechModelManufaacturer");
                _TechModelManufaacturer = StructuralObject.SetValidValue(value, true, "TechModelManufaacturer");
                ReportPropertyChanged("TechModelManufaacturer");
                OnTechModelManufaacturerChanged();
            }
        }
        private global::System.String _TechModelManufaacturer;
        partial void OnTechModelManufaacturerChanging(global::System.String value);
        partial void OnTechModelManufaacturerChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TechModelName
        {
            get
            {
                return _TechModelName;
            }
            set
            {
                OnTechModelNameChanging(value);
                ReportPropertyChanging("TechModelName");
                _TechModelName = StructuralObject.SetValidValue(value, true, "TechModelName");
                ReportPropertyChanged("TechModelName");
                OnTechModelNameChanged();
            }
        }
        private global::System.String _TechModelName;
        partial void OnTechModelNameChanging(global::System.String value);
        partial void OnTechModelNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Id_Color
        {
            get
            {
                return _Id_Color;
            }
            set
            {
                OnId_ColorChanging(value);
                ReportPropertyChanging("Id_Color");
                _Id_Color = StructuralObject.SetValidValue(value, "Id_Color");
                ReportPropertyChanged("Id_Color");
                OnId_ColorChanged();
            }
        }
        private Nullable<global::System.Int32> _Id_Color;
        partial void OnId_ColorChanging(Nullable<global::System.Int32> value);
        partial void OnId_ColorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_problemDescryption
        {
            get
            {
                return _id_problemDescryption;
            }
            set
            {
                Onid_problemDescryptionChanging(value);
                ReportPropertyChanging("id_problemDescryption");
                _id_problemDescryption = StructuralObject.SetValidValue(value, "id_problemDescryption");
                ReportPropertyChanged("id_problemDescryption");
                Onid_problemDescryptionChanged();
            }
        }
        private Nullable<global::System.Int32> _id_problemDescryption;
        partial void Onid_problemDescryptionChanging(Nullable<global::System.Int32> value);
        partial void Onid_problemDescryptionChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_requestStatys
        {
            get
            {
                return _id_requestStatys;
            }
            set
            {
                Onid_requestStatysChanging(value);
                ReportPropertyChanging("id_requestStatys");
                _id_requestStatys = StructuralObject.SetValidValue(value, "id_requestStatys");
                ReportPropertyChanged("id_requestStatys");
                Onid_requestStatysChanged();
            }
        }
        private Nullable<global::System.Int32> _id_requestStatys;
        partial void Onid_requestStatysChanging(Nullable<global::System.Int32> value);
        partial void Onid_requestStatysChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> completionDate
        {
            get
            {
                return _completionDate;
            }
            set
            {
                OncompletionDateChanging(value);
                ReportPropertyChanging("completionDate");
                _completionDate = StructuralObject.SetValidValue(value, "completionDate");
                ReportPropertyChanged("completionDate");
                OncompletionDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _completionDate;
        partial void OncompletionDateChanging(Nullable<global::System.DateTime> value);
        partial void OncompletionDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String repairParts
        {
            get
            {
                return _repairParts;
            }
            set
            {
                OnrepairPartsChanging(value);
                ReportPropertyChanging("repairParts");
                _repairParts = StructuralObject.SetValidValue(value, true, "repairParts");
                ReportPropertyChanged("repairParts");
                OnrepairPartsChanged();
            }
        }
        private global::System.String _repairParts;
        partial void OnrepairPartsChanging(global::System.String value);
        partial void OnrepairPartsChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> masterId
        {
            get
            {
                return _masterId;
            }
            set
            {
                OnmasterIdChanging(value);
                ReportPropertyChanging("masterId");
                _masterId = StructuralObject.SetValidValue(value, "masterId");
                ReportPropertyChanged("masterId");
                OnmasterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _masterId;
        partial void OnmasterIdChanging(Nullable<global::System.Int32> value);
        partial void OnmasterIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> clientID
        {
            get
            {
                return _clientID;
            }
            set
            {
                OnclientIDChanging(value);
                ReportPropertyChanging("clientID");
                _clientID = StructuralObject.SetValidValue(value, "clientID");
                ReportPropertyChanged("clientID");
                OnclientIDChanged();
            }
        }
        private Nullable<global::System.Int32> _clientID;
        partial void OnclientIDChanging(Nullable<global::System.Int32> value);
        partial void OnclientIDChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK_Request_Color", "Color")]
        public Color Color
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("YP1Model.FK_Request_Color", "Color").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("YP1Model.FK_Request_Color", "Color").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Color> ColorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("YP1Model.FK_Request_Color", "Color");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Color>("YP1Model.FK_Request_Color", "Color", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK_Comment_Request", "Comment")]
        public EntityCollection<Comment> Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("YP1Model.FK_Comment_Request", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("YP1Model.FK_Comment_Request", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__Request__Id_home__440B1D61", "HomeTechType")]
        public HomeTechType HomeTechType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HomeTechType>("YP1Model.FK__Request__Id_home__440B1D61", "HomeTechType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HomeTechType>("YP1Model.FK__Request__Id_home__440B1D61", "HomeTechType").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HomeTechType> HomeTechTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HomeTechType>("YP1Model.FK__Request__Id_home__440B1D61", "HomeTechType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HomeTechType>("YP1Model.FK__Request__Id_home__440B1D61", "HomeTechType", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__Request__id_prob__45F365D3", "ProblemDescryption")]
        public ProblemDescryption ProblemDescryption
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemDescryption>("YP1Model.FK__Request__id_prob__45F365D3", "ProblemDescryption").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemDescryption>("YP1Model.FK__Request__id_prob__45F365D3", "ProblemDescryption").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProblemDescryption> ProblemDescryptionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemDescryption>("YP1Model.FK__Request__id_prob__45F365D3", "ProblemDescryption");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProblemDescryption>("YP1Model.FK__Request__id_prob__45F365D3", "ProblemDescryption", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__Request__id_requ__46E78A0C", "RequestStatus")]
        public RequestStatus RequestStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestStatus>("YP1Model.FK__Request__id_requ__46E78A0C", "RequestStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestStatus>("YP1Model.FK__Request__id_requ__46E78A0C", "RequestStatus").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RequestStatus> RequestStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestStatus>("YP1Model.FK__Request__id_requ__46E78A0C", "RequestStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RequestStatus>("YP1Model.FK__Request__id_requ__46E78A0C", "RequestStatus", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="RequestStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RequestStatus : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта RequestStatus.
        /// </summary>
        /// <param name="id_RequestStatus">Исходное значение свойства Id_RequestStatus.</param>
        public static RequestStatus CreateRequestStatus(global::System.Int32 id_RequestStatus)
        {
            RequestStatus requestStatus = new RequestStatus();
            requestStatus.Id_RequestStatus = id_RequestStatus;
            return requestStatus;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_RequestStatus
        {
            get
            {
                return _Id_RequestStatus;
            }
            set
            {
                if (_Id_RequestStatus != value)
                {
                    OnId_RequestStatusChanging(value);
                    ReportPropertyChanging("Id_RequestStatus");
                    _Id_RequestStatus = StructuralObject.SetValidValue(value, "Id_RequestStatus");
                    ReportPropertyChanged("Id_RequestStatus");
                    OnId_RequestStatusChanged();
                }
            }
        }
        private global::System.Int32 _Id_RequestStatus;
        partial void OnId_RequestStatusChanging(global::System.Int32 value);
        partial void OnId_RequestStatusChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RequestStatuse
        {
            get
            {
                return _RequestStatuse;
            }
            set
            {
                OnRequestStatuseChanging(value);
                ReportPropertyChanging("RequestStatuse");
                _RequestStatuse = StructuralObject.SetValidValue(value, true, "RequestStatuse");
                ReportPropertyChanged("RequestStatuse");
                OnRequestStatuseChanged();
            }
        }
        private global::System.String _RequestStatuse;
        partial void OnRequestStatuseChanging(global::System.String value);
        partial void OnRequestStatuseChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__Request__id_requ__46E78A0C", "Request")]
        public EntityCollection<Request> Request
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Request>("YP1Model.FK__Request__id_requ__46E78A0C", "Request");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Request>("YP1Model.FK__Request__id_requ__46E78A0C", "Request", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта sysdiagrams.
        /// </summary>
        /// <param name="name">Исходное значение свойства name.</param>
        /// <param name="principal_id">Исходное значение свойства principal_id.</param>
        /// <param name="diagram_id">Исходное значение свойства diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="Type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Type : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Type.
        /// </summary>
        /// <param name="idType">Исходное значение свойства IdType.</param>
        public static Type CreateType(global::System.Int32 idType)
        {
            Type type = new Type();
            type.IdType = idType;
            return type;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdType
        {
            get
            {
                return _IdType;
            }
            set
            {
                if (_IdType != value)
                {
                    OnIdTypeChanging(value);
                    ReportPropertyChanging("IdType");
                    _IdType = StructuralObject.SetValidValue(value, "IdType");
                    ReportPropertyChanged("IdType");
                    OnIdTypeChanged();
                }
            }
        }
        private global::System.Int32 _IdType;
        partial void OnIdTypeChanging(global::System.Int32 value);
        partial void OnIdTypeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type1
        {
            get
            {
                return _Type1;
            }
            set
            {
                OnType1Changing(value);
                ReportPropertyChanging("Type1");
                _Type1 = StructuralObject.SetValidValue(value, true, "Type1");
                ReportPropertyChanged("Type1");
                OnType1Changed();
            }
        }
        private global::System.String _Type1;
        partial void OnType1Changing(global::System.String value);
        partial void OnType1Changed();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__User__typeId__4BAC3F29", "User")]
        public EntityCollection<User> User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("YP1Model.FK__User__typeId__4BAC3F29", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("YP1Model.FK__User__typeId__4BAC3F29", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YP1Model", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта User.
        /// </summary>
        /// <param name="userId">Исходное значение свойства UserId.</param>
        public static User CreateUser(global::System.Int32 userId)
        {
            User user = new User();
            user.UserId = userId;
            return user;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String F
        {
            get
            {
                return _F;
            }
            set
            {
                OnFChanging(value);
                ReportPropertyChanging("F");
                _F = StructuralObject.SetValidValue(value, true, "F");
                ReportPropertyChanged("F");
                OnFChanged();
            }
        }
        private global::System.String _F;
        partial void OnFChanging(global::System.String value);
        partial void OnFChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String I
        {
            get
            {
                return _I;
            }
            set
            {
                OnIChanging(value);
                ReportPropertyChanging("I");
                _I = StructuralObject.SetValidValue(value, true, "I");
                ReportPropertyChanged("I");
                OnIChanged();
            }
        }
        private global::System.String _I;
        partial void OnIChanging(global::System.String value);
        partial void OnIChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String O
        {
            get
            {
                return _O;
            }
            set
            {
                OnOChanging(value);
                ReportPropertyChanging("O");
                _O = StructuralObject.SetValidValue(value, true, "O");
                ReportPropertyChanged("O");
                OnOChanged();
            }
        }
        private global::System.String _O;
        partial void OnOChanging(global::System.String value);
        partial void OnOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, "phone");
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private Nullable<global::System.Int64> _phone;
        partial void OnphoneChanging(Nullable<global::System.Int64> value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, true, "login");
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passsword
        {
            get
            {
                return _passsword;
            }
            set
            {
                OnpassswordChanging(value);
                ReportPropertyChanging("passsword");
                _passsword = StructuralObject.SetValidValue(value, true, "passsword");
                ReportPropertyChanged("passsword");
                OnpassswordChanged();
            }
        }
        private global::System.String _passsword;
        partial void OnpassswordChanging(global::System.String value);
        partial void OnpassswordChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> typeId
        {
            get
            {
                return _typeId;
            }
            set
            {
                OntypeIdChanging(value);
                ReportPropertyChanging("typeId");
                _typeId = StructuralObject.SetValidValue(value, "typeId");
                ReportPropertyChanged("typeId");
                OntypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _typeId;
        partial void OntypeIdChanging(Nullable<global::System.Int32> value);
        partial void OntypeIdChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK_Comment_User", "Comment")]
        public EntityCollection<Comment> Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("YP1Model.FK_Comment_User", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("YP1Model.FK_Comment_User", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("YP1Model", "FK__User__typeId__4BAC3F29", "Type")]
        public Type Type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Type>("YP1Model.FK__User__typeId__4BAC3F29", "Type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Type>("YP1Model.FK__User__typeId__4BAC3F29", "Type").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Type> TypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Type>("YP1Model.FK__User__typeId__4BAC3F29", "Type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Type>("YP1Model.FK__User__typeId__4BAC3F29", "Type", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
