//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForYP.DatabaseHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemDescryption
    {
        public int Id_ProblemDescryption { get; set; }
        public string ProblemDescryption1 { get; set; }
    }
}
