//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForYP.DatabaseHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int requestID { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<int> Id_homeTechType { get; set; }
        public string TechModelManufaacturer { get; set; }
        public string TechModelName { get; set; }
        public Nullable<int> Id_Color { get; set; }
        public string problemDescryption { get; set; }
        public Nullable<int> id_requestStatys { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> masterId { get; set; }
        public Nullable<int> clientID { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual HomeTechType HomeTechType { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
