//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForYP.DatabaseHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int requestID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<int> Id_homeTechType { get; set; }
        public Nullable<int> Id_homeTechModel { get; set; }
        public Nullable<int> id_problemDescryption { get; set; }
        public Nullable<int> id_requestStatys { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> masterId { get; set; }
        public Nullable<int> clientID { get; set; }
    
        public virtual HomeTechModel HomeTechModel { get; set; }
        public virtual HomeTechType HomeTechType { get; set; }
        public virtual ProblemDescryption ProblemDescryption { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
    }
}
