//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForYP.DatabaseHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public Nullable<long> phone { get; set; }
        public string login { get; set; }
        public string passsword { get; set; }
        public Nullable<int> typeId { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
